//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackToYourFuture.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Place
    {
        public Place()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int PlaceID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }

        public string PlaceName { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
